server:
  port: 8080

spring:
  application:
    name: api-layer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

slack:
  webhook:
    url: "http://localhost:8080/mock/slack/webhook"
  oauth:
    client-id: "mock-client-id"
    client-secret: "mock-client-secret"
    redirect-uri: "http://localhost:8080/api/slack/oauth/callback"
    scopes: "user.profile,channels:read,chat:write"
    token-expiration-seconds: 3600
    enabled: false

openai:
  api:
    key: "mock-key"
    url: "http://localhost:8080/mock/openai"
    enabled: false

redis:
  host: localhost
  port: 6379
  enabled: false
