server:
  port: 8080

spring:
  application:
    name: api-layer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

app:
  encryption:
    key: "mock-encryption-key-for-development"
  base-url: "http://localhost:8080"

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

slack:
  oauth:
    client-id: "mock-client-id"
    client-secret: "mock-client-secret"
    redirect-uri: "http://localhost:8080/api/slack/oauth/callback"
    scopes: "user.profile,channels:read,chat:write"
    token-expiration-seconds: 3600

openai:
  api:
    key: "mock-openai-key"
    url: "http://localhost:8080/mock/openai"

external:
  openai:
    enabled: false
    api:
      key: "mock-key"
      url: "http://localhost:8080/mock/openai"

  redis:
    enabled: false
    host: localhost
    port: 6379
