server:
  port: 8085

spring:
  application:
    name: api-layer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: SA
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db,diskSpace
        liveness:
          include: ping
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    diskspace:
      enabled: true
    db:
      enabled: true
    ping:
      enabled: true
    defaults:
      enabled: true

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

app:
  base-url: http://localhost:8085
  encryption:
    key: "your-secret-key-here-must-be-at-least-32-bytes-long"

encryption:
  key: "mock-encryption-key-for-development"

slack:
  oauth:
    client-id: "mock-client-id"
    client-secret: "mock-client-secret"
    redirect-uri: "http://localhost:8080/api/slack/oauth/callback"
    scopes: "user.profile,channels:read,chat:write"
    token-expiration-seconds: 3600

openai:
  api:
    key: "mock-openai-key"
    url: "http://localhost:8080/mock/openai"

external:
  openai:
    enabled: false
    api:
      key: "mock-key"
      url: "http://localhost:8080/mock/openai"

  redis:
    enabled: false
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    com.enterprise.agents: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
